### PR TITLE
Fix 1408 tutor only books

### PR DESCRIPTION
**Pull request by therealmarv**
* sort fields
* add tutor_only fields

### CODE REVIEW

**Comment by therealmarv** [comment]
Probably this PR needs synchronisation with REX if we break things with a new JSON entry `"tutor_only": false`

**Review by rnathuji — APPROVED** [review]

**Comment by therealmarv** [comment]
@Bkblodget do we have an okay from REX that this can be merged?

**Review by philschatz — APPROVED** [review]
Do you know if there is a way to uniquely serialize JSON? I recall an npm package that does this.

**Comment by therealmarv** [comment]
I don't know, sorry.

**Comment by therealmarv** [comment]
Just for reference where ABL is probably only used in REX:

https://github.com/openstax/rex-web/blob/master/concourse/update-content/script.bash

**Pull request merged**
