### PR TITLE
Adding 1e books to the ABL

### PR DESCRIPTION
**Pull request by theresamasciale**
Added 1e books to ABL

### CODE REVIEW

**Comment by theresamasciale** [comment]
dangit it failed :(

**Comment by rnathuji** [comment]
@theresamasciale - I see...it looks like some of these new additions don't have slugs defined in the new [book-slugs.json](https://github.com/openstax/content-manager-approved-books/blob/master/book-slugs.json). I don't see them in the [CMS list](https://openstax.org/apps/cms/api/v2/pages?type=books.Book&fields=cnx_id&limit=100) either, but perhaps that is because they're 1e books that are not available through REX (?).

**Comment by theresamasciale** [comment]
@rnathuji yes we're trying to add them to rex. Should I go ahead and update the slug json?

**Comment by rnathuji** [comment]
@theresamasciale - Ah, I see. Yes, you can go ahead and add corresponding entries to the slug.json for the books that need them. 

Out of curiosity, how does that work in terms of defining the slug for these new additions to REX? Do you already know what you want them to be, do you generate them in the CMS first and adjust as needed, ...? Just trying to understand some of that process better as it's a bit opaque to me :)

**Comment by theresamasciale** [comment]
@rnathuji Just updated the slug list! 

So for the slugs: when the book page is created, the slugs are auto-generated (we can change them if we want, but we usually just keep whatever is generated). For these 1e's, I went to their old cms pages and copied over their slugs (just to be consistent). Intro to Sociology was the only one that for some reason didn't have a page in the cms so I just made it the same as the 2e, but removed "2e" from the slug.

**Review by rnathuji — APPROVED** [review]

**Pull request merged**
