### PR TITLE
Errata  Update to ABL

### PR DESCRIPTION
**Pull request by ne-newton**
Update ABL to reflect errata updates, which includes moving many many books to be served from GitHub, rather than archive.

### CODE REVIEW

**Comment by ne-newton** [comment]
One thing to check for in this PR is that all books that have been added to the GitHub section of the ABL have also been fully removed from the Archive part of the ABL (both book and versions).

**Comment by ne-newton** [comment]
Some spot checking of the book UUIDs and the commit SHAs would also be helpful, due to the amount of cutting and pasting that happened in this PR

**Comment by TylerZeroMaster** [comment]
@ne-newton I wrote test that found that `algebra-and-trigonometry` appears in both a git book entry and an archive entry. Would you say that this situation would **_always_** be considered an error? I am wondering if we should add this test to this repository's testing script.

**Comment by ne-newton** [comment]
@TylerZeroMaster I think it would be good to add that as a test. However, in maybe less than a month, we will hopefully only have git books. So it depends on the work load of adding it as a test.

**Review by TylerZeroMaster — CHANGES_REQUESTED** [review]
I rewrote the test to give a list of all duplicates instead of stopping at the first. Here are the results. I think you fixed one, but there are still three more.


```
Duplicate book found: {"uuid":"13ac107a-f15f-49d2-97e8-60ab2e3b519c","slug":"algebra-and-trigonometry"}
Duplicate book found: {"uuid":"9b08c294-057f-4201-9f48-5d6ad992740d","slug":"college-algebra"}
Duplicate book found: {"uuid":"507feb1e-cfff-4b54-bc07-d52636cecfe3","slug":"college-algebra-corequisite-support"}
Duplicate book found: {"uuid":"fd53eae1-fa23-47c7-bb1b-972349835c3c","slug":"precalculus"}
```

**Comment by ne-newton** [comment]
@TylerZeroMaster I couldn't find the others in the archive section (not searching by slug or col#) - maybe they are showing up as they are all in the same bundle as `algebra-and-trigonometry`?

**Comment by ne-newton** [comment]
Or have you already taken them out for me?

**Review by TylerZeroMaster — APPROVED** [review]

**Comment by TylerZeroMaster** [comment]
No, the problem was on my end. My abl.json was outdated.

**Pull request merged**
